sever:
  address: localhost
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daemoing
    username: daemo
    password: super-daemo-ing

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: always

  # Swagger springdoc-ui Configuration
  springdoc:
    packages-to-scan: com.daemoing.daemo
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    swagger-ui:
      path: index.html            # Swagger UI ?? => localhost:8080/swagger-ui/index.html
      tags-sorter: alpha            # alpha: ??? ? ?? ??, method: HTTP Method ? ??
      operations-sorter: alpha      # alpha: ??? ? ?? ??, method: HTTP Method ? ??
    api-docs:
      path: /api-docs/json
      groups:
        enabled: true
    cache:
      disabled: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=
  refresh-token-validity-in-seconds: 1209600 # 14?
  access-token-validity-in-seconds: 43200 # 12??


